const users = [
  {
    id: 0,
    fname: "Andrew",
    lname: "Taylor",
    username: "drewjtaylor",
    email: "drew.j.taylor1@gmail.com",
    address1: '123 Main Street',
    address2: null,
    city: 'Pinellas Park',
    avatarImage: "images/drewjtaylorAvatar.jpg",
    isAdmin: true,
    isMember: true,
  },
  {
    id: 1,
    fname: "John",
    lname: "Smith",
    username: "jsmithy",
    email: "fakeemail@mailinator.com",
    avatarImage: "images/JohnSmithAvatar.jpg",
    isAdmin: false,
    isMember: true,
  },
  {
    id: 2,
    fname: "Suzy",
    lname: "Queue",
    username: "qtasticsue",
    email: "suzy@mailinator.com",
    avatarImage: "images/SuzyQAvatar.jpg",
    isAdmin: false,
    isMember: true,
  },
  {
    id: 3,
    fname: "Heather",
    lname: "Anderson",
    username: "unicornsforever24",
    email: "isitarhinonoaunicorn@mailinator.com",
    avatarImage: "images/unicorn.jpg",
    isAdmin: false,
    isMember: false,
  },
  {
    id: 4,
    fname: "Joseph",
    lname: "Kilmar",
    username: "kilmanjaro",
    email: "anotherfakeemail@mailinator.com",
    avatarImage: "images/AliceKilmarAvatar.png",
    isAdmin: false,
    isMember: false,
  },
];

export default users;
